POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IiIsImV4cCI6MTc0MDc4MjQxMywidXNlcklkIjoiIn0.KAF9EMT5lABubQ-DYExkepacQFXiIEC_Q1VqR2exUSo

{
  "name": "Test",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}